// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import tailwindcss from '@tailwindcss/vite';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';

import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '../../'); // allow Vite to read root node_modules

export default defineConfig({
  site: 'https://bjmcd.dev',
  base: '/docs/swe',
  trailingSlash: 'always',

  markdown: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [[rehypeKatex, { output: 'htmlAndMathml' }]],
  },

  integrations: [
    starlight({
      title: 'SWE Docs',
      customCss: ['katex/dist/katex.min.css'],

      // Tag all pages in this app as space=SWE for Pagefind filters
      head: [{ tag: 'meta', attrs: { name: 'pagefind:filters', content: '{"space":"SWE"}' } }],

      // Cross-space search: include JHU’s index
      pagefind: {
        indexWeight: 2, // prefer local results
        mergeIndex: [
          {
            bundlePath: 'https://bjmcd.dev/docs/jhu/pagefind',
            baseUrl: 'https://bjmcd.dev/docs/jhu/',
            indexWeight: 0.8,
            mergeFilter: { space: 'JHU' },
          },
        ],
      },

      // Sidebar (autogenerated like JHU)
      sidebar: [
        { 
          label: 'Ansi-C',
          collapsed: true,
          items: [
            { label: 'Introduction',  autogenerate: { directory: 'ansi-c/intro',   collapsed: true } }, //1
            { label: 'Anatomy of a C Program', autogenerate: { directory: 'ansi-c/anatomy', collapsed: true } }, //2
            { label: 'Control Flow', autogenerate: { directory: 'ansi-c/controlflow', collapsed: true } }, //3
            { label: 'Functions & Program Structure', autogenerate: { directory: 'ansi-c/funcprogramstruct', collapsed: true } }, //4
            { label: 'Pointers & Dynamic Memory', autogenerate: { directory: 'ansi-c/pointdyn', collapsed: true } }, //5
            { label: 'Arrays & Strings', autogenerate: { directory: 'ansi-c/arraystr', collapsed: true } }, //6
            { label: 'Structures & Data Organization', autogenerate: { directory: 'ansi-c/structdataorg', collapsed: true } }, //7
            { label: 'File Input/Output', autogenerate: { directory: 'ansi-c/fileio', collapsed: true } }, //8
            { label: 'Memory Management & Heap', autogenerate: { directory: 'ansi-c/advmemmang', collapsed: true } }, //9
            { label: 'Preprocessor & Modularity', autogenerate: { directory: 'ansi-c/preprocmodprog', collapsed: true } }, //10
            { label: 'Low-Level C', autogenerate: { directory: 'ansi-c/lowlevelc', collapsed: true } }, //11
            { label: 'Debugging, Testing, Error Handling', autogenerate: { directory: 'ansi-c/debugtesterr', collapsed: true } }, //12
            { label: 'Concurrency', autogenerate: { directory: 'ansi-c/concurrency', collapsed: true } }, //13
          ],
        },
        { label: 'Reference', collapsed: true, autogenerate: { directory: 'reference' } },
      ],
    }),
  ],

  vite: {
    plugins: [tailwindcss()],
    server: { fs: { allow: [repoRoot] } }, // fix Vite allow-list during dev
  },
});
