// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import tailwindcss from '@tailwindcss/vite';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';

import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '../../'); // allow Vite to read root node_modules

export default defineConfig({
  site: 'https://bjmcd.dev',
  base: '/docs/swe',
  trailingSlash: 'always',

  markdown: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [[rehypeKatex, { output: 'htmlAndMathml' }]],
  },

  integrations: [
    starlight({
      title: 'SWE Docs',
      customCss: ['katex/dist/katex.min.css'],

      // Tag all pages in this app as space=SWE for Pagefind filters
      head: [{ tag: 'meta', attrs: { name: 'pagefind:filters', content: '{"space":"SWE"}' } }],

      // Cross-space search: include JHU’s index
      pagefind: {
        indexWeight: 2, // prefer local results
        mergeIndex: [
          {
            bundlePath: 'https://bjmcd.dev/docs/jhu/pagefind',
            baseUrl: 'https://bjmcd.dev/docs/jhu/',
            indexWeight: 0.8,
            mergeFilter: { space: 'JHU' },
          },
        ],
      },

      // Sidebar (autogenerated like JHU)
      sidebar: [
        { 
          label: 'Guides',
          collapsed: false,
          items: [
            { label: 'Ansi-C',  autogenerate: { directory: 'guides/fall',   collapsed: true } },
            { label: 'Spring Guides', autogenerate: { directory: 'guides/spring', collapsed: true } },
          ],
        },
        { label: 'Reference', collapsed: true, autogenerate: { directory: 'reference' } },
      ],
    }),
  ],

  vite: {
    plugins: [tailwindcss()],
    server: { fs: { allow: [repoRoot] } }, // fix Vite allow-list during dev
  },
});
